- task: AzureCLI@2
  displayName: 'Terraform Init, Plan and Apply'
  inputs:
    azureSubscription: 'AzureSPN'  # Match your service connection name
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Terraform Init, Plan, Apply"
      cd infra
      terraform init
      terraform plan
      terraform apply -auto-approve
  env:
    ARM_CLIENT_ID: $(servicePrincipalId)
    ARM_CLIENT_SECRET: $(servicePrincipalKey)
    ARM_SUBSCRIPTION_ID: $(subscriptionId)
    ARM_TENANT_ID: $(tenantId)
