- task: AzureCLI@2
  displayName: 'Terraform Init, Plan and Apply'
  inputs:
    azureSubscription: 'AzureSPN'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Setting up ARM_* from Azure CLI"
      export ARM_CLIENT_ID=$(az account show --query user.name -o tsv)
      export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
      export ARM_TENANT_ID=$(az account show --query tenantId -o tsv)
      echo "Running Terraform"
      cd infra
      terraform init
      terraform plan
      terraform apply -auto-approve
